
CREATE TABLE Pedidos(
    Numero char(12) NOT NULL,
    FechaEmision datetime NOT NULL,
    FechaEntrega datetime NULL,
    CodigoCliente char(20) NULL,
    TotalBruto decimal(10,2) NULL,
    Descuento decimal(10,2) NULL,
    Impuesto decimal(10,2) NULL,
    Cargo decimal(10,2) NULL,
    TotalPedido decimal(10,2) NULL,
    PorcentajeDescuento decimal(10,2) NULL,
    Vendedor char(5) NULL,
    Comentarios text NULL,
    Tarifa char(5) NULL,
    Almacen char(5) NULL,
    Peso decimal(10,2) NULL,
    Estatus char(2) NULL,
    Usuario char(50) NULL,
    Cambio decimal(10,2) NULL,
    Moneda char(4) NULL,
    TotalBruto2 decimal(10,2) NULL,
    Descuento2 decimal(10,2) NULL,
    Impuesto2 decimal(10,2) NULL,
    Cargo2 decimal(10,2) NULL,
    TotalPedido2 decimal(10,2) NULL,
    IdMoneda int NULL,
    Registro int NOT NULL PRIMARY KEY AUTO_INCREMENT 
);